/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LayoutRouteImport } from "./routes/_layout"
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index"
import { Route as AuthAuthRouteImport } from "./routes/auth/_auth"
import { Route as AuthAuthIndexRouteImport } from "./routes/auth/_auth/index"
import { Route as AuthAuthRegisterRouteImport } from "./routes/auth/_auth/register"
import { Route as AuthAuthLoginRouteImport } from "./routes/auth/_auth/login"
import { Route as LayoutDashboardSalesRouteImport } from "./routes/_layout/dashboard/sales"
import { Route as LayoutDashboardAnalyticsRouteImport } from "./routes/_layout/dashboard/analytics"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: "/auth/_auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthIndexRoute = AuthAuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthRoute,
} as any)
const LayoutDashboardSalesRoute = LayoutDashboardSalesRouteImport.update({
  id: "/dashboard/sales",
  path: "/dashboard/sales",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardAnalyticsRoute =
  LayoutDashboardAnalyticsRouteImport.update({
    id: "/dashboard/analytics",
    path: "/dashboard/analytics",
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/auth": typeof AuthAuthRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/dashboard/analytics": typeof LayoutDashboardAnalyticsRoute
  "/dashboard/sales": typeof LayoutDashboardSalesRoute
  "/auth/login": typeof AuthAuthLoginRoute
  "/auth/register": typeof AuthAuthRegisterRoute
  "/auth/": typeof AuthAuthIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof LayoutIndexRoute
  "/dashboard/analytics": typeof LayoutDashboardAnalyticsRoute
  "/dashboard/sales": typeof LayoutDashboardSalesRoute
  "/auth/login": typeof AuthAuthLoginRoute
  "/auth/register": typeof AuthAuthRegisterRoute
  "/auth": typeof AuthAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_layout": typeof LayoutRouteWithChildren
  "/auth/_auth": typeof AuthAuthRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/dashboard/analytics": typeof LayoutDashboardAnalyticsRoute
  "/_layout/dashboard/sales": typeof LayoutDashboardSalesRoute
  "/auth/_auth/login": typeof AuthAuthLoginRoute
  "/auth/_auth/register": typeof AuthAuthRegisterRoute
  "/auth/_auth/": typeof AuthAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/auth"
    | "/"
    | "/dashboard/analytics"
    | "/dashboard/sales"
    | "/auth/login"
    | "/auth/register"
    | "/auth/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard/analytics"
    | "/dashboard/sales"
    | "/auth/login"
    | "/auth/register"
    | "/auth"
  id:
    | "__root__"
    | "/_layout"
    | "/auth/_auth"
    | "/_layout/"
    | "/_layout/dashboard/analytics"
    | "/_layout/dashboard/sales"
    | "/auth/_auth/login"
    | "/auth/_auth/register"
    | "/auth/_auth/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/auth/_auth": {
      id: "/auth/_auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/_auth/": {
      id: "/auth/_auth/"
      path: "/"
      fullPath: "/auth/"
      preLoaderRoute: typeof AuthAuthIndexRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    "/auth/_auth/register": {
      id: "/auth/_auth/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    "/auth/_auth/login": {
      id: "/auth/_auth/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    "/_layout/dashboard/sales": {
      id: "/_layout/dashboard/sales"
      path: "/dashboard/sales"
      fullPath: "/dashboard/sales"
      preLoaderRoute: typeof LayoutDashboardSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/dashboard/analytics": {
      id: "/_layout/dashboard/analytics"
      path: "/dashboard/analytics"
      fullPath: "/dashboard/analytics"
      preLoaderRoute: typeof LayoutDashboardAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashboardAnalyticsRoute: typeof LayoutDashboardAnalyticsRoute
  LayoutDashboardSalesRoute: typeof LayoutDashboardSalesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashboardAnalyticsRoute: LayoutDashboardAnalyticsRoute,
  LayoutDashboardSalesRoute: LayoutDashboardSalesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
  AuthAuthIndexRoute: typeof AuthAuthIndexRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
  AuthAuthIndexRoute: AuthAuthIndexRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthAuthRoute: AuthAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
